language: c
compiler:
  - gcc

script: 
  - autoconf && autoheader && ./configure --$BUNDLEDLIBTOM-bundled-libtom CFLAGS="-O2 -Wall -Wno-pointer-sign" && make
  - ./dropbearkey -t rsa -f testrsa
  - ./dropbearkey -t dss -f testdss
  - ./dropbearkey -t ecdsa -f testec256 -s 256
  - ./dropbearkey -t ecdsa -f testec384 -s 384
  - ./dropbearkey -t ecdsa -f testec521 -s 521


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libz-dev libtomcrypt-dev libtommath-dev

env: 
  - BUNDLEDLIBTOM=enable
  - BUNDLEDLIBTOM=disable


